@startuml

package "agi_data_coverage (Edit-DB)" {
  class "Datenabdeckung" as da
  class "Teilflaeche" as tf
  
  da "1" -- "1..n" tf
}

package "DataCoverage (SIMI)" {
  class "SubArea" as sa
  class "Published\nSubArea" as pa
  
  pa "*" -- "0..1" sa
}

tf .right.> sa : Datensynchronisation


legend
  Master: 
  - Edit-Db für Geometrie und Beziehung
  - SIMI für den Rest
  - Identifikatoren müssen übereinstimmen
  
  Ablauf Datensynchronisation:
  - db2db Teilflaeche --> SubArea mit Flag "imported"
  - update SubArea where exists in "imported", "existing"
  - insert SubArea where exists in "imported", not in "existing"
  - soft delete SubArea where exists in "existing", not in "imported"
  - hard delete alle mit Flag "imported"
end legend

@enduml