@startuml
package Theme {

  abstract class "DataSetView" as dsv << package data >>
  class "Theme\nPublication" as tp
  class "Theme" as th
  
  package Organisation {
    class "OrgUnit" as ou
    note right
      AGI ist als tech. 
      OrgUnit aller Themes
      hier auch erfasst.
    end note
    
    class "Agency" as ag
    class "SubOrg" as so
    
    ag "1" -right- "*" so
  
    ou <|-- ag
    ou <|-- so
  }
  
  package DataCoverage {
    class "Extent (b2)" as ex
    class "Published\nExtent" as pe
    class "DataCoverage" as dc
    
    tp "1" -- "1..n" pe
    pe "*" -- "0..1" ex
  }
  
  th "*" -- "1" dc
  th "1" -- "*" tp
  th "*" -- "1" ou : "fach"
  tp "0..1" -- "1-n" dsv : "(b1)"
}
legend
  b1 - Constraints: 
  - Kein Gemisch Vector - "Non Vector"
  - Vector nur aus einem Schema
  - Keine DSV mit Filter-View
  
  b2:
  - Geometrie als wkb in bytea
  - IUD via GRETL von Edit-DB
  - Hat Attribut DataCoverage (group identifier) zweck IUD
  
  DSV oder DS? --> IAM klären bei geschützten tp
  By the way: Constraint zur Konsistenz der Attribut-Zuweisungen?
end legend
@enduml