@startuml
package Theme {

  class "Theme\nPublication" as tp
  class "Theme" as th
  class "FileType" as ft 
  
  abstract class "DataSetView" as dsv << package data >>
  abstract class "DataProduct" as dp << package product >>
  
  package Organisation {
    class "OrgUnit" as ou
    note right
      AGI ist als tech. 
      OrgUnit aller Themes
      hier auch erfasst.
    end note
    
    class "Agency" as ag
    class "SubOrg" as so
    
    ag "1" -right- "*" so
  
    ou <|-- ag
    ou <|-- so
  }
  
  package DataCoverage {
    class "Extent" as ex
    class "Published\nExtent" as pe
    class "DataCoverage" as dc
    
    tp "1" -- "1..n" pe
    pe "*" -- "0..1" ex
  }
  
  th "*" -- "1" dc
  th "1" -- "*" tp
  th "*" -- "1" ou : "fach"
  th "0..1" .. "*" dp : "Darstellungen (b1)"
  tp "0..1" -- "1-n" dsv
  tp "*" -- "*" ft
}

legend
  b1: Offen ob Herleitung oder geführte Beziehung
end legend
@enduml