version: '3'

services:
  db:
    image: postgis/postgis:14-3.3
    environment:
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=simi
      - PGDATA=/var/lib/postgresql/data/pgdata
    ports:
      - "5432:5432" # for create db action
  await-db:
    image: postgis/postgis:14-3.3
    command: /var/lib/postgresql/data/await-db/await.sh
    environment:
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=simi
    volumes:
      - "./await-db:/var/lib/postgresql/data/await-db"
  simi:
    image: sogis/simi
    environment:
    - CUBA_DATASOURCE_USERNAME=postgres
    - CUBA_DATASOURCE_PASSWORD=postgres
    - CUBA_DATASOURCE_DBNAME=simi
    - CUBA_DATASOURCE_HOST=db
    - CUBA_DATASOURCE_PORT=5432
    ports:
      - "8080:8080"