alter table SIMITHEME_THEME add constraint FK_SIMITHEME_THEME_ON_DATA_OWNER foreign key (DATA_OWNER_ID) references SIMITHEME_ORG_UNIT(ID);
create unique index IDX_SIMITHEME_THEME_UK_IDENTIFIER on SIMITHEME_THEME (IDENTIFIER);
create index IDX_SIMITHEME_THEME_ON_DATA_OWNER on SIMITHEME_THEME (DATA_OWNER_ID);
