create unique index IDX_SIMITHEME_FILE_TYPE_UK_KUERZEL on SIMITHEME_FILE_TYPE (KUERZEL);
create unique index IDX_SIMITHEME_FILE_TYPE_UK_NAME on SIMITHEME_FILE_TYPE (NAME);
create unique index IDX_SIMITHEME_FILE_TYPE_UK_MIME_TYPE on SIMITHEME_FILE_TYPE (MIME_TYPE);
