@startuml
package "Einführung" {
    [E1: Benutzerdokumentation] as e1
    [E2: GO-LIVE] as e2
    [E3: Schulungen] as e3
    [E4: Ausserbetriebnahmen] as e4


    e1 --> e2
    e2 --> e3
    e2 --> e4
}
@enduml