@startuml
package "Realisierung" {
    [R1: SIMI "Low Code"] as r1
    [R2: Model-Reader] as r2
    [R3: GRETL-Integration] as r3
    [R4: Datenmigrationsskripte] as r4
    [R5: Config-Deployment] as r5
    [R6: «Know your GDI» Auswertung] as r6
    [R7: Integrationstest] as r7

    r1 --> r2
    r1 --> r4
    r4 --> r5
    r4 --> r6

    r1 --> r7
    r2 --> r7
    r3 --> r7
    r4 --> r7
    r5 --> r7
    r6 --> r7
}
@enduml