@startuml
package "Jenkins" {
	together {
    	[sql2json] as sj
        () shell as sji
        sji - sj
    }
    
    together {
    	[json2qml] as jq
        () shell as jqi
        jqi - jq
    }
    
    together {
    	[OC-Client] as oc
        () shell as oci
        oci - oc
    }
    
    together {
    	[Docker-Client] as dc
        () shell as dci
        dci - dc
    }
    
    [Jenkins-Pipeline] as pipe
    
    pipe --> dci
    pipe --> oci
    pipe --> jqi
    pipe --> sji
}
legend
Docker und oder OC können auch via Jenkins-Plugin verwendet werden, sofern daraus
konkrete Vorteile resultieren.
endlegend
@enduml