# Zu beachten: "databases" ist ein Postgresql cluster, welches die Datenbanken "simi" und "postgres" umfasst:
# - "simi": Von der cuba-applikation "simi" genutzte und gemanagte metadatenbank.
# - "postgres": Zieldatenbank für den Schemareader. Ist "Geo-Enabled" und enthält Beispieldatensätze.
version: "3"
services:
  schemareader:
    image: sogis/simi_schemareader:2.0
    environment:
      - SPRING_APPLICATION_JSON={"dbs":[{"key":"geodb","url":"jdbc:postgresql://databases:5432/postgres","user":"postgres","pass":"postgres"}]}
    ports:
      - "8081:8080"
  databases:
    image: postgis/postgis:11-2.5-alpine
    environment:
      - POSTGRES_PASSWORD=postgres
      - PGDATA=/var/lib/postgresql/data/pgdata
    ports:
      - "5432:5432"
    volumes:
      - "./gitignored/pgdata_simi_v2:/var/lib/postgresql/data/pgdata"
