@startuml
package "Konzept" {
    [K1: Simi Umsetzungsfragen] as k1
    [K2: Transformation] as k2
    [K3: Simi Hauptanwendungsfälle] as k3
    [K4: Magicbutton-Pipeline] as k4
    [K5: ModelReader] as k5
    [K6: GRETL-Schnittstelle] as k6
    [K7: DataProduct-Service] as k7

    k3 --> k4
    k3 --> k5
}
@enduml