SET ROLE admin;
GRANT USAGE ON ALL SEQUENCES IN SCHEMA simi TO simi_write;
GRANT SELECT, INSERT, UPDATE, DELETE ON ALL TABLES IN SCHEMA simi TO simi_write;
GRANT SELECT ON ALL TABLES IN SCHEMA simi TO simi_read;
GRANT simi_read TO bjsvw;
