alter table SIMITHEME_PUBLISHED_SUB_AREA_HELPER drop column SUB_AREA_IDENT__U67068 cascade ;
alter table SIMITHEME_PUBLISHED_SUB_AREA_HELPER drop column THEME_PUB_DATA_CLASS_OVERRIDE__U03562 cascade ;
alter table SIMITHEME_PUBLISHED_SUB_AREA_HELPER drop column THEME_PUB_DATA_CLASS__U46340 cascade ;

--je
alter table SIMITHEME_PUBLISHED_SUB_AREA_HELPER drop column THEME_PUBLICATION_ID cascade ;
alter table SIMITHEME_PUBLISHED_SUB_AREA_HELPER drop column SUB_AREA_ID cascade ;