# Setzt voraus, dass eine Postgresql-Datenbank mit den untenstehenden Parametern
# erreichbar (gestartet) ist.
version: "3.7"
services:
  simi:
    image: sogis/simi:latest
    environment:
      - CUBA_DATASOURCE_USERNAME=postgres
      - CUBA_DATASOURCE_PASSWORD=postgres
      - CUBA_DATASOURCE_JDBCURL=jdbc:postgresql://localhost:5432/postgres?currentSchema=public
      - CUBA_AUTOMATICDATABASEUPDATE=true
    ports:
      - "8080:8080"
    network_mode: "host"

