-- begin PRODUCT_DATA_SET_VIEW
alter table PRODUCT_DATA_SET_VIEW add constraint FK_PRODUCT_DATA_SET_VIEW_ON_FEATURE_INFO foreign key (FEATURE_INFO_ID) references FI_FEATURE_INFO(ID)^
create index IDX_PRODUCT_DATA_SET_VIEW_ON_FEATURE_INFO on PRODUCT_DATA_SET_VIEW (FEATURE_INFO_ID)^
-- end PRODUCT_DATA_SET_VIEW
-- begin FI_LAYER_RELATION
alter table FI_LAYER_RELATION add constraint FK_FI_LAYER_RELATION_ON_DATA_SET_VIEW foreign key (DATA_SET_VIEW_ID) references PRODUCT_DATA_SET_VIEW(ID)^
alter table FI_LAYER_RELATION add constraint FK_FI_LAYER_RELATION_ON_FEATURE_INFO foreign key (FEATURE_INFO_ID) references FI_FEATURE_INFO(ID)^
create index IDX_FI_LAYER_RELATION_ON_DATA_SET_VIEW on FI_LAYER_RELATION (DATA_SET_VIEW_ID)^
create index IDX_FI_LAYER_RELATION_ON_FEATURE_INFO on FI_LAYER_RELATION (FEATURE_INFO_ID)^
-- end FI_LAYER_RELATION
