@startuml
abstract class "DataSetView (DSV)" as dsv << package Product >>

package "Template" {
    class "Template" as tpl
    class "LayerRelation" as lr

    tpl "1" -- "1..n" lr
}

lr "*" -- "1" dsv

@enduml