@startuml
abstract class "DataSetView (DSV)" as dsv << package Product >>

package FeatureInfo {
  class "FeatureInfo" as fi
  class "LayerRelation" as lr
}

fi "1" -left- "1..*" lr : "    "
lr "*" -- "1" dsv
@enduml