@startuml
class "PostgresTable" as pgt << package Data >>

package Flow {
  class "Job" as job
  class "LayerUsage" as lu
}

job "1" -- "1..*" lu
lu "*" -- "1" pgt

legend bottom
Mock entity "PostgresTable" attributes:
- tableName: String(100)
- schemaName: String(100)
- dbName: String(100)

--> @NamePattern [dbName].[schemaName].[tableName]
end legend
@enduml