@startuml
abstract class "DataSetView (DSV)" as dsv << package Product >>

package "Bouncer" {
	class "ProtectedService" as ps
    class "Ressource" as res
    class "LayerRelation" as lr
}

res "1" -- "1..n" lr
lr "*" -- "1" dsv

res "1-n" -- "1" ps
@enduml