@startuml
class "SingleLayer (SL)" as sl << package Core >>

package Contact {
	class "ContactRole" as cr
    class "DataContact" as dc
    class "Contact" as con
    class "Person" as pers
    class "Organisation" as org
}

sl "1" -up- "1..n" dc
cr "1 " -right- "1..n" dc : "       "
dc "1..n" -- "1" con

con <|-- pers
con <|-- org

pers "1..n" -right- "  1" org : "       "
@enduml