@startuml
package "Product" {
  abstract class "DataSetView (DSV)" as dsv
  class "Map (Map)" as map {}
}


package "CCC Client" {

  class "CCC Client" as ccc {}

  class "Locator Layer" as ll {}

  class "Notify Layer" as nl {}


  ccc "*" -- "1" map

  ccc "1" -- "*" ll
  ll "*" -- "1" dsv

  ccc "1" -- "*" nl
  nl "*" -- "1" dsv
}
@enduml