apiVersion: v1
kind: Template
metadata:
  name: ${APPNAME}-template                                        
labels:
  template: ${APPNAME}-template
  app: ${APPNAME}
objects:
- apiVersion: v1
  kind: ImageStream
  metadata:
    name: ${APPNAME}
    labels:
      app: ${APPNAME}
  spec:
    tags:
    - from:
        kind: DockerImage
        name: ${IMAGENAME}:${TAG}
      importPolicy:
        scheduled: ${{IMPORT_POLICY_SCHEDULED}}
      name: ${TAG}
- apiVersion: v1
  kind: DeploymentConfig
  metadata:
    name: ${APPNAME}
  spec:
    replicas: ${{REPLICA_COUNT}}
    selector:                                                       
      app: ${APPNAME}
    strategy:
      type: Rolling
    template:
      metadata:
        labels:
          app: ${APPNAME}
      spec:
        containers:
        - name: ${APPNAME}
          envFrom:
          - secretRef:
              name: simi-db-credentials
          - secretRef:
              name: simi-ldap-credentials
          env:
          - name: CUBA_WEB_REQUIREPASSWORDFORNEWUSERS
            value: "false"
          - name: CUBA_WEB_STANDARDAUTHENTICATIONUSERS
            value: admin
          - name: CUBA_WEB_PRODUCTIONMODE
            value: "true"
          - name: SIMI_CONFIG_STOPONINCOMPLETE
            value: "true"
          - name: SIMI_GITSEARCH_URL
            value: https://api.github.com/search/code
          - name: SIMI_GITSEARCH_REPOS
            value: sogis/gretljobs|oereb/jobs
          - name: SIMI_PUBLISHJOB_BASEURL
            value: fuu
          - name: SIMI_PUBLISHJOB_POLLTIMEOUT
            value: "5"
          - name: SIMI_PUBLISHJOB_SECTOKEN
            value: secret
          - name: SIMI_SCHEMAREADER_URL
            value: ${SIMI_SCHEMAREADER_URL}
          - name: CUBA_AUTOMATICDATABASEUPDATE
            value: "false"
          - name: CUBA_WEB_LDAP_ENABLED
            value: "true"
          readinessProbe:
            failureThreshold: 3
            httpGet:
              path: /app/dispatch/health
              port: 8080
              scheme: HTTP
            initialDelaySeconds: 15
            periodSeconds: 10
            successThreshold: 1
            timeoutSeconds: 1
          livenessProbe:
            failureThreshold: 3
            httpGet:
              path: /app/dispatch/health
              port: 8080
              scheme: HTTP
            initialDelaySeconds: 15
            periodSeconds: 10
            successThreshold: 1
            timeoutSeconds: 1
          resources:
            limits:
              cpu: ${CPU_LIMIT}
              memory: ${MEMORY_LIMIT}
            requests:
              cpu: ${CPU_REQUEST}
              memory: ${MEMORY_REQUEST}
    triggers:
    - type: ConfigChange
    - type: ImageChange
      imageChangeParams:
        automatic: true
        containerNames:
        - ${APPNAME}
        from:
          kind: ImageStreamTag
          name: ${APPNAME}:${TAG}
- apiVersion: v1
  kind: Service
  metadata:
    name: ${APPNAME}
  spec:
    ports:
    - name: 80-tcp
      port: 80
      protocol: TCP
      targetPort: 8080
    selector:
      app: ${APPNAME}
- apiVersion: route.openshift.io/v1
  kind: Route
  metadata:
    name: ${APPNAME}
  spec:
    host: ${HOSTNAME}
    port:
      targetPort: 80-tcp
    to:
      kind: Service
      name: ${APPNAME}
parameters:
- name: APPNAME
  description: "Name of the App"
  required: true
- name: IMAGENAME
  description: "Name of the docker image"
  required: true
- name: TAG
  description: "The Docker image tag to use (e.g. latest)"
  value: latest
- name: IMPORT_POLICY_SCHEDULED
  description: "Regularly check for changed image?"
  value: "false"
- name: REPLICA_COUNT
  description: "Number of replicas to run"
  value: "1"
- name: HOSTNAME
  description: "The hostname for the route"
- name: CPU_REQUEST
  description: "The minimum amount of CPU the container is guaranteed."
  value: 250m
- name: CPU_LIMIT
  description: "The maximum amount of CPU the container is allowed to use when running."
  value: "1"
- name: MEMORY_REQUEST
  description: "The minimum amount of memory the container is guaranteed."
  value: 200Mi
- name: MEMORY_LIMIT
  description: "The maximum amount of memory the container is allowed to use when running."
  value: 600Mi
- name: SIMI_SCHEMAREADER_URL
  description: "Url to the simi-schemareader"
